###
Get http://localhost:3003/student/age?id=3


###
Post http://localhost:3003/student/create
Content-Type: application/json

{
   "id": "005" ,
   "name":  "Magali",
   "email": "maga@gmail.com",
   "birthdate": "1993-12-14" 
   }


###
Delete http://localhost:3003/student/remove?id=1

###
put  http://localhost:3003/student/remove/class?id=3



###
put http://localhost:3003/teacher/class/remove?id=6


###
Post http://localhost:3003/teacher/create
Content-Type: application/json

{
   "id": "006" ,
   "name":  "Darvas",
   "email": "darvas@gmail.com",
   "birthdate": "1988-03-02" 
   }


   
###
put  http://localhost:3003/teacher/add
Content-Type: application/json

{
   "id": "10" ,
   "class_id":  "2"
   }


###
get http://localhost:3003/students/3

###
get http://localhost:3003/teachers/2


###
get http://localhost:3003/students?hobbies=1



###
Put http://localhost:3003/class
Content-Type: application/json

{
   "id": "2" ,
   "program":  "2"
 }

###
get http://localhost:3003/teachers?expertise=3

