###
Get http://localhost:3003/student/age?id=3


###
Post http://localhost:3003/student/create
Content-Type: application/json

{
   "id": "001" ,
   "name":  "Camily",
   "email": "camily@gmail.com",
   "birthdate": "2002-09-02" ,
   "class_id":"1"
   }

###
Delete http://localhost:3003/student/remove?id=1

###
put  http://localhost:3003/student/remove/class?id=3

